---
kind: Secret
apiVersion: v1
metadata:
  name: kroxy-idp-secret-file
  namespace: acaleph
data:
  idp-secret: ekUwWEZoeER6TV9NT2haS3lrYWpMc3BieEh4cHlyMzAyT1BRdWRFRFNBUg==

---
kind: Service
apiVersion: v1
metadata:
  name: kroxy
  namespace: acaleph
  labels:
    app: kroxy
    type: proxy
spec:
  selector:
    app: kroxy
    type: proxy
  ports:
    - name: service
      protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer

---
kind: ReplicationController
apiVersion: v1
metadata:
  name: kroxy-v1
  namespace: acaleph
  labels:
    app: kroxy
    type: proxy
spec:
  replicas: 1
  selector:
    app: kroxy
    type: proxy
  template:
    metadata:
      name: kroxy
      labels:
        app: kroxy
        type: proxy
    spec:
      volumes:
        - name: kroxy-idp-secret
          secret:
            secretName: kroxy-idp-secret-file
      containers:
        - name: kroxy
          image: quay.io/acaleph/kroxy
          env:
            - name: KROXY_TOKEN_FILE
              value: /var/run/secrets/kubernetes.io/serviceaccount/token
            - name: KROXY_K8S_API
              value: https://kubernetes.default
          ports:
            - name: service
              containerPort: 8080
              hostPort: 8080
          volumeMounts:
            - name: kroxy-idp-secret
              mountPath: /.secret
              readOnly: true
          imagePullPolicy: Always
